### ISSUE TITLE
请兼容支持下最新的SDWebImage 4.0.0

### ISSUE THREAD

**Issue by Smeegol** [Sunnyyoung/MJPhotoBrowser#2]
![image](https://cloud.githubusercontent.com/assets/1212201/23150167/6681284c-f82c-11e6-99fc-8cb127fff4d8.png)
我是用CocoaPods集成的MJPhotoBrowser，SDWebImage 4.0.0之后跟之前的API变化了，编译失败，请更新支持下，并同步到CocoaPods，谢谢！

**Comment by Sunnyyoung** [comment]
@Smeegol 
你好，这个项目已经不再维护，推荐使用[SYPhotoBrowser](https://github.com/Sunnyyoung/SYPhotoBrowser)

**Comment by Smeegol** [comment]
@Sunnyyoung 你觉得哪个iOS开源图片浏览器各方面比较好呢，其实我觉得你这个不错，简单，满足简易需求，可惜不维护了……[MWPhotoBrowser](https://github.com/mwaterfall/MWPhotoBrowser) 这个如何？
